### ISSUE TITLE
criminalrecord:fetch

### ISSUE THREAD

**Issue by phantomora** [jonassvensson4/jsfour-criminalrecord#10]
I'm getting the TriggerServerCallback => [jsfour-criminalrecord:fetch] does not exist
my load order is register, mdc, criminalrecord, dna. i saw in fourms you said there is a load order but i have not found it anywhere.

**Comment by jnsvns** [comment]
Well if you read my comment at the forum I replied to the guy saying:

"Can’t do anything about it, the event exists. Maybe you’ve messed up the start order?"

If they're started before ESX that may cause some problems.

**Comment by phantomora** [comment]
i decided to fresh install criminal and now it works
