### ISSUE TITLE
Uncaught reference error $ not defined.

### ISSUE THREAD

**Issue by neoreturns** [jonassvensson4/jsfour-criminalrecord#11]
Hello!

I am developing my own server, I understand that the Javascript is calling back to the URL and looking for the response. $ Undefined is usually jQuery not loading properly. I have over 50 scripts working and its only jsfour causing issues. 

I've reinstalled/updated and I have the correct foldername jsfour-criminalrecord

![image](https://user-images.githubusercontent.com/34321024/56085232-44ff2300-5e40-11e9-8a80-c48163fdc91c.png)

**Comment by jnsvns** [comment]
You're getting an error in the jquery. Have no idea how you can get that error. 

- Corrputed files was my first guess but I guess you've tried to redownload it?
- If that doesn't work you can try to change this line in index.html
`<script src="assets/js/jquery.js" type="text/javascript"></script>`
to
`<script src="nui://game/ui/jquery.js" type="text/javascript"></script>`

**Comment by neoreturns** [comment]
Thanks for your quick response. I've many mods working off jQuery and JS. Will try this fix and return with the answer.

**Comment by neoreturns** [comment]
It seems that the jquery.js is corrupted. By re-downloading and replacing it from the official jquery site, fixed the error. Im confused as I downloaded from here the master copy and using that. May want to check it. Many thanks for your support and fantastic work. We use jsfour-criminal records and also jsfour-idcard, excellent mods. Keep up the great work.

**Comment by jnsvns** [comment]
Yeah files can get corrupted when you download them. I don't know why but yeah I'm glad it worked. And thanks for the kind words :)
