### ISSUE TITLE
no action when pressing "E"

### ISSUE THREAD

**Issue by cjself** [jonassvensson4/jsfour-criminalrecord#12]
I have downloaded as instructed. when i walk into the blue circle i am prompted to press "E" but nothing happens.

**Comment by hyp3rstrike** [comment]
Can confirm.

**Comment by jnsvns** [comment]
I just downloaded the github version and it works fine for me. Check your consoles for errors.

**Comment by cjself** [comment]
Okay I’ll try and look at it.

**Comment by iJeeves** [comment]
Also having this issue currently, no doubt it's something i've done or not done correctly. I followed the instructions and tried a fresh install. 

Getting this on console when i press 'E' at the documents
es_extended: TriggerServerCallback => [jsfour-criminalrecord:fetch] does not exist

Fairly new to this sorter thing go easy. :)

Cheers.

UPDATE : Didn't start it after the other esx mods. MY BAD!

**Comment by ericb160** [comment]
need help please
SQL query:


USE `essentialmode`
MySQL said: Documentation

#1044 - Access denied for user 'zap415197-1'@'%' to database 'essentialmode'
