### ISSUE TITLE
Marker not showing

### ISSUE THREAD

**Issue by RKillinger37** [jonassvensson4/jsfour-criminalrecord#13]
Hi,

So when I was in the main PD station, I could see the marker and use it. But, when I changed to coords to the sheriff station in Paleto Bay, the marker isn't showing. Here are the coords I used. Am i going wrong somewhere? Is there something else I need to change as well? Also, do the coords need to be in long format or can I use the 2 decimal point format? (example: 111.11)

Config.Marker = {
	Pos   = {x = -448.78094482422, y = 6011.8715820313, z = 31.71639251709},
	Size  = {x = 2.0, y = 2.0, z = 1.0},
	Color = {r = 26, g = 55, b = 186},
	Hint = 'Press ~INPUT_PICKUP~ to open the criminal record',
	Type = 27,
}

**Comment by jnsvns** [comment]
The marker is probably under the ground. Use noclip and play around with the Z value.

Please use the FiveM native documentation. The positions is a float value.
https://runtime.fivem.net/doc/natives/#_0x28477EC23D892089
