### ISSUE TITLE
Add to Police Menu ?

### ISSUE THREAD

**Issue by jokid64** [jonassvensson4/jsfour-criminalrecord#16]
Hi, 
Is there a way to add to police menu ? Tried with jsfour-criminalrecord:fetch event but it would be too easy ^^ 

Thx

**Comment by jnsvns** [comment]
Of course there's a way to add it to a menu.

Create a event in the client.lua and copy the stuff in the key event thread, row 61 to 68 and place it inside the event.

**Comment by jokid64** [comment]
But when I paste 61-68 rows : 
```
ESX.TriggerServerCallback('jsfour-criminalrecord:fetch', function( d )
				SetNuiFocus(true, true)

				SendNUIMessage({
				  action = "open",
					array  = d
				})
		  end, data, 'start')

```
I've got the legitimate error about the esx_policejob dont have UI frame !

**Comment by jnsvns** [comment]
Paste them where?

**Comment by jokid64** [comment]
in police job, menu label : 

> {label = 'Criminal Records',      value = 'criminalrecords'},

Then : 			

> elseif action == 'criminalrecords' then
> ESX.TriggerServerCallback('jsfour-criminalrecord:fetch', function( d )
> SetNuiFocus(true, true)
> 
> SendNUIMessage({
> action = "open",
> array  = d
> })
> end, data, 'start')

**Comment by jnsvns** [comment]
I never told you to paste it in esx_policejob? I told you to create an event in the client.lua. Esx_policejob doesn't even have a file called client.lua. You'll then use the event in your menu

**Comment by jokid64** [comment]
Owww ok sorry didnt get it ... 

Like : 

```
 RegisterNetEvent('jsfour-criminalrecord:fetch')
 AddEventHandler('jsfour-criminalrecord:fetch', function()
 	Citizen.CreateThread(function()
 	while true do
 		Wait(0)
 		if IsControlJustReleased(0, 38) and inMarker then
 			ESX.TriggerServerCallback('jsfour-criminalrecord:fetch', function( d )
 				SetNuiFocus(true, true)
 
 				SendNUIMessage({
 				  action = "open",
 					array  = d
 				})
 		  end, data, 'start')
 		end
 	end
 end)
 end)
```

Then in menu :

```
 
 elseif action == 'criminalrecords' then
 TriggerServerEvent('jsfour-criminalrecord:fetch')


```
Will test it now

**Comment by jnsvns** [comment]
No?

1. Create a event in the client.lua
2. Paste row 61 to 68 in the created event
3. Use the event in your menu

I'm sorry but I can't help you anymore. I've tried to explain it 3 times now

**Comment by MackOG** [comment]
@jokid64 did you get it too work?

**Comment by jokid64** [comment]
@MackOG no, here what ive tried :

In client.lua
```
RegisterNetEvent('jsfour-criminalrecord:fetch')
AddEventHandler('jsfour-criminalrecord:fetch', function()
			ESX.TriggerServerCallback('jsfour-criminalrecord:fetch', function( d )
				SetNuiFocus(true, true)

				SendNUIMessage({
				  action = "open",
					array  = d
				})
		  end, data, 'start')
end)
```
and this in menu :
```
		elseif action == 'records' then
						TriggerServerEvent('jsfour-criminalrecord:fetch')
```

But this not works, idk what to do now, a bit useless if i cant have it in a menu

**Comment by MackOG** [comment]
@jokid64 Yup i agree. If i get it working ill let you know.

**Comment by jnsvns** [comment]
@jokid64 

You register a client event, which is correct
`RegisterNetEvent('jsfour-criminalrecord:fetch')`

But then you're trying to run a server event?
`TriggerServerEvent('jsfour-criminalrecord:fetch')`

**Comment by jokid64** [comment]
Ow man ... it seems working late drive to strange mistakes, fixed, it works, thx u

**Comment by yahyacansahan** [comment]
how did you solve the problem?

**Comment by aGift4u** [comment]
yahyacan 
change TriggerServerEvent('jsfour-criminalrecord:fetch') to 
TriggerEvent('jsfour-criminalrecord:fetch') in your menu.

**Comment by yahyacansahan** [comment]
@aGift4u thanks

**Comment by Ryytel** [comment]
I am very new to this and I'm very confused on what I'm supposed to do. Can somebody please tell me if I'm doing it correctly.

So I add all this in the client.lua
`{label = 'Criminal Records', value = 'criminalrecords'}

elseif action == 'criminalrecords' then
	TriggerEvent('jsfour-criminalrecord:fetch')

RegisterNetEvent('jsfour-criminalrecord:fetch')
AddEventHandler('jsfour-criminalrecord:fetch', function()
			ESX.TriggerServerCallback('jsfour-criminalrecord:fetch', function( d )
				SetNuiFocus(true, true)

				SendNUIMessage({
				  action = "open",
					array  = d
				})
		  end, data, 'start')
end))`
and that's it?

**Comment by Ryytel** [comment]
I'm very new to this and this thread is very confusing.
Am I understanding this correctly.

So all this goes in the client.lua?

`{label = 'Criminal Records', value = 'criminalrecords'}`

`elseif action == 'criminalrecords' then
	TriggerEvent('jsfour-criminalrecord:fetch')`

`RegisterNetEvent('jsfour-criminalrecord:fetch')
AddEventHandler('jsfour-criminalrecord:fetch', function()
			ESX.TriggerServerCallback('jsfour-criminalrecord:fetch', function( d )
				SetNuiFocus(true, true)

				SendNUIMessage({
				  action = "open",
					array  = d
				})
		  end, data, 'start')
end)`

**Comment by Ryytel** [comment]
I did all this but the menu just doesn't open
