### ISSUE TITLE
Disable DOB checking ? 

### ISSUE THREAD

**Issue by zelizz** [jonassvensson4/jsfour-criminalrecord#17]
Hello, how can I remove the DOB checking in users database ? Players never respect the format then when policemen want to add someone in the criminal record, they cant cause of DOB format not respected when users registered when arrived in server ... 

I disabled the 'required' in the HTML but then I look into server.lua jsfour-criminalrecord:add, tried  some things but cant do it ... 

btw thats the best criminal record over fivem ;)

**Comment by jnsvns** [comment]
You'll have to change some code in order to remove it completely since it's a key feature to be able to identify a player. I won't help you re-code it. This is something you have to do by yourself

It would be easier to format the DOB when players register in the first place
