### ISSUE TITLE
more than 3 spot

### ISSUE THREAD

**Issue by JeremCyberCorsaire** [jonassvensson4/jsfour-criminalrecord#18]
Hi,
I've tried to create more than 3 reading spot for the records, but each time there is one doesn't work. I don't know why.

**Comment by jnsvns** [comment]
Not an issue, the script is configured to only have 1 marker. You have to change it in client.lua

**Comment by JeremCyberCorsaire** [comment]
I think you didn’t understand,
I’ve already changed the client.lua
For 2 markers, its ok
For 3 markers, its ok
For 4 markers, it doesn’t work, one of the 4 markers doesn’t work

**Comment by jnsvns** [comment]
Still not an issue since this is not a part of the original script.
