### ISSUE TITLE
When press "E" get an error on console

### ISSUE THREAD

**Issue by DiabolicMzz** [jonassvensson4/jsfour-criminalrecord#19]
When i finish the record and press add i get this error :

![error2](https://user-images.githubusercontent.com/52853153/61169873-20f3d080-a55a-11e9-8a15-944e6647951d.png)

Everything else is working fine.. (mdc)

**Comment by jnsvns** [comment]
It's trying to decode the skin string that it's fetching from your users table. Looks like it returns empty. Check your database and log what the result returns.
