### ISSUE TITLE
Everything is classified as a cop

### ISSUE THREAD

**Issue by KoolAiddTV** [jonassvensson4/jsfour-criminalrecord#21]
I can't seem to get it to show the records
https://prntscr.com/ouupkq

**Comment by jnsvns** [comment]
With that small amount of information I can't really help you since it's working fine for me. If you haven't made any changes to the script I suggest you that you try to re-download it. If that doesn't work you could remove the classified function.

**Comment by KoolAiddTV** [comment]
Yeah sorry man I'm not to sure how to provide more information on it. It was the clean script with no changes. I just removed the classified functions. Thanks man, great work!
