### ISSUE TITLE
can't move the Mouse

### ISSUE THREAD

**Issue by Kikidiia** [jonassvensson4/jsfour-criminalrecord#22]
Hey, 
Since Yesterday I can't move the Mouse. My Friends too.
I don't know what happen or did u Update the script?

**Comment by jnsvns** [comment]
I mean you can see when I made the last commit to this repo so no I haven't updated it? 

And what do you mean by "I can't move the mouse". Please be a bit more specific.. When does it stop working? Can you move it at all?

**Comment by jnsvns** [comment]
No response
