### ISSUE TITLE
Cannot move after i close menu

### ISSUE THREAD

**Issue by Dejvi1** [jonassvensson4/jsfour-criminalrecord#24]
Hey there can i get some help with window that stuck movement,camera etc? I can only move mouse cursor and thats all..

**Comment by jnsvns** [comment]
If you can close it but you get stuck after closing it means that it can't send a post request back to the client. Which means that you're probably using the wrong name of the folder.

What name are you using?

**Comment by Dejvi1** [comment]
jsfour-criminalrecord

**Comment by jnsvns** [comment]
If you would've used that name you wouldn't get stuck. I would suggest that you redownload the resource.

**Comment by Dejvi1** [comment]
ah yeah i was missing name i had only jsfourcriminalrecord. Thanks for reply mate ! :*
