### ISSUE TITLE
Error - No person was found, first name, last name or dob could be wrong

### ISSUE THREAD

**Issue by TheKetur55** [jonassvensson4/jsfour-criminalrecord#3]
Hello ,
Thank you for this script
My only problem right now is the error:
Error - No name was found, first name, last name or dob could be wrong
İ have
John
Doe
1997-03-02
Murder
1Y
1997-10-10
Description: kpcsdpkpsdkcds
Where does the error come from?

Sorry İts Translate :D
KeyTur#1357

**Comment by jnsvns** [comment]
Exactly what the error says?
first name, last name or dob could be wrong

"The first name, last name and DOB needs to be spelled the exact same way they're spelt in the database"

**Comment by TheKetur55** [comment]
![20181014123412_1](https://user-images.githubusercontent.com/19953505/46914942-7ab87180-cfad-11e8-8701-8f48fb34c4e7.jpg)

**Comment by jnsvns** [comment]
Yeah I know that's the error, I created it. Send me a screenshot of that users values in the database

**Comment by TheKetur55** [comment]
![zz](https://user-images.githubusercontent.com/19953505/46915011-53ae6f80-cfae-11e8-99f2-7330d7677be3.PNG)

**Comment by TheKetur55** [comment]
The database is empty

**Comment by jnsvns** [comment]
the USERS database

**Comment by TheKetur55** [comment]
![aa](https://user-images.githubusercontent.com/19953505/46915117-7d1bcb00-cfaf-11e8-9956-355dea4a6595.PNG)

**Comment by jnsvns** [comment]
You have a table called users in your database. Send me a screenshot of the user that you're trying to add.

https://prnt.sc/l5vx2p
