### ISSUE TITLE
Error - No person was found first name last name or dob could be wrong

### ISSUE THREAD

**Issue by infernal1337** [jonassvensson4/jsfour-criminalrecord#7]
I have problem i cant add players to criminal record.
![usun](https://user-images.githubusercontent.com/45695389/49693008-536ec280-fb60-11e8-9d41-9ecf00230333.jpg)
![usun2](https://user-images.githubusercontent.com/45695389/49693018-93ce4080-fb60-11e8-9351-f1bdf0d9ce2e.png)
Please help me. I give upper screenshot of error and screenshot of my database users.

**Comment by jnsvns** [comment]
You're using the DOB 1997-12-12, since you kindly provided a screenshot of your database that doesn't show that DOB, does it even exist?

**Comment by infernal1337** [comment]
Its not my screensoht of game but same problem i can make screenshot when im putting name of game someone and its same ;p

**Comment by jnsvns** [comment]
So you have a user called Jean Loius with the DOB 1997-12-12 in the database?
