### ISSUE TITLE
impossible search

### ISSUE THREAD

**Issue by BLRPFR** [jonassvensson4/jsfour-criminalrecord#8]
Hello Jsfour,
When I try to search for a player's criminal record, that's what happens.
Thanking you for your work.
![0_20181209112344_1](https://user-images.githubusercontent.com/45731183/49696141-ae76d880-fba5-11e8-9475-4ad8d2b4c571.png)
![0_20181209112358_1](https://user-images.githubusercontent.com/45731183/49696143-b0d93280-fba5-11e8-9cd2-49783852576c.png)

**Comment by jnsvns** [comment]
Have you updated the script?

**Comment by BLRPFR** [comment]
Yes, this night.

**Comment by jnsvns** [comment]
Just downloaded the github-version. Works fine for me. 

You sure that you're using the latest version? Clear cache maybe

**Comment by BLRPFR** [comment]
I re-downloaded the script, but same error. This is what I do if I look at the console.
![capture](https://user-images.githubusercontent.com/45731183/49697575-a45ed500-fbb9-11e8-8ddd-ee6de89da230.PNG)

**Comment by jnsvns** [comment]
Yeah it will give you that error when you're clicking a undefined user. Open up the server.lua and let me see row 67

**Comment by BLRPFR** [comment]
My sql base
![capture2](https://user-images.githubusercontent.com/45731183/49697621-1b946900-fbba-11e8-8d3e-dd8fd621f222.PNG)
![capture3](https://user-images.githubusercontent.com/45731183/49697622-1b946900-fbba-11e8-991d-500c3e39ef0e.PNG)

**Comment by BLRPFR** [comment]
My row 67 
![capture](https://user-images.githubusercontent.com/45731183/49697665-8ba2ef00-fbba-11e8-9cd1-e7d436f58694.PNG)

**Comment by jnsvns** [comment]
Looks about right. Have no idea why yours isn't working. I guess you have to debug it since it's working fine for me.

Add `console.log(data);` in the html/assets/js/init.js like I did here: https://prnt.sc/lsnqay

**Comment by BLRPFR** [comment]
This is
![0_20181209140941_1](https://user-images.githubusercontent.com/45731183/49697807-29e38480-fbbc-11e8-9c4b-71dc950a9ee1.png)

**Comment by jnsvns** [comment]
Yeah that also looks right. I have no idea how I'm supposed to help you since I can't recreate your problem.

I'll ask around to see if anyone else has this problem and then I'll get back to you

**Comment by jnsvns** [comment]
FiveM updated it again so it should be working if you revert to the old version.

**Comment by jonassvensson4** [comment]
I'll revert the github-version once I've tested it out to make sure the old version is working

**Comment by AdrineX** [comment]
Old version is working fine with me, with the newest FiveM update

**Comment by jnsvns** [comment]
Yeah old version seems to be working now so you can revert it back.

I might revert the github version later

**Comment by BLRPFR** [comment]
It's fine for me.
tack och hej från paris
